# Generated by Django 5.1.4 on 2025-01-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
