# Generated by Django 5.1.4 on 2025-01-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatsession_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='data',
            new_name='datas',
        ),
    ]
