# Generated by Django 5.1.4 on 2025-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_data_chatsession_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefile',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basefile',
            name='region',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
