# Generated by Django 5.1.4 on 2025-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_basefile_date_basefile_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='basefile',
            name='region',
        ),
    ]
