# Generated by Django 5.1.4 on 2025-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_basefile_date_remove_basefile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefile',
            name='date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='basefile',
            name='region',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
