# Generated by Django 5.1.4 on 2025-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_excelfile'),
        ('api', '0007_alter_basefile_region'),
    ]

    operations = [
    ]
