# Generated by Django 5.1.4 on 2025-01-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0004_excelfile_0007_alter_basefile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefile',
            name='isResultFile',
            field=models.BooleanField(default=False),
        ),
    ]
